'use strict';

module.exports = function (router) {

  /* Set the XSRF-TOKEN cookie on first request (Generated by lusca) */
  router.use(function (req, res, next) {
    res.cookie('XSRF-TOKEN', res.locals._csrf);
    next();
  });

  /**
   * Define all front-end routes here.
   */
  router.get([
    /* Pages */
    '/', '/theme',

    /* Error routes */
    '/lost', '/forbidden',

    /* Users */
    '/users/sign-up', '/users/sign-in', '/users/recover'

  ], function (req, res) {
    /* Render the base layout */
    res.render('pages/main');
  });

};
